package Vistas;

import Model.*;
import Repositorio.*;
import Servicio.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TablaComentarios extends javax.swing.JPanel {

    private final ContactoService contactoService = new ContactoService(new ContactoRepositorio());

    public TablaComentarios() {
        initComponents();
        cargarComentarios();
    }

    private void cargarComentarios() {
        DefaultTableModel modelo = (DefaultTableModel) tablaClientes.getModel();
        modelo.setRowCount(0);

        List<Contacto> comentarios = contactoService.obtenerTodos();
        if (comentarios.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay comentarios registrados todavía.");
            return;
        }

        for (Contacto c : comentarios) {
            modelo.addRow(new Object[]{
                c.getIdContacto(),
                c.getNombre(),
                c.getEmpresa(),
                c.getEmail(),
                c.getTelefono(),
                c.getServicio(),
                c.getMensaje(),
                c.getFechaEnvio()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnPDF = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido", "FecNac", "Email", "Telefono", "UsuaAtendi", "Sueldo", "Horario", "Contraseña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Empresa", "Email", "Teléfono", "Servicio", "Mensaje", "Fechas de Envio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaClientes);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Clientes Asignados");

        btnPDF.setBackground(new java.awt.Color(30, 45, 60));
        btnPDF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnPDF.setText("PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPDF)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPDF)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        try {
            // Obtener los comentarios desde el servicio
            List<Contacto> comentarios = contactoService.obtenerTodos();

            if (comentarios.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay comentarios para exportar.");
                return;
            }

            // Crear el documento PDF
            com.itextpdf.text.Document documento = new com.itextpdf.text.Document();
            String ruta = System.getProperty("user.home") + "/Desktop/Comentarios.pdf";
            com.itextpdf.text.pdf.PdfWriter.getInstance(documento, new java.io.FileOutputStream(ruta));
            documento.open();

            // Título del documento
            com.itextpdf.text.Paragraph titulo = new com.itextpdf.text.Paragraph("📋 Lista de Comentarios Registrados\n\n",
                    new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 18, com.itextpdf.text.Font.BOLD));
            titulo.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
            documento.add(titulo);

            // Crear tabla PDF con encabezados
            com.itextpdf.text.pdf.PdfPTable tabla = new com.itextpdf.text.pdf.PdfPTable(8); // 8 columnas
            tabla.setWidthPercentage(100);

            // Encabezados
            String[] encabezados = {"ID", "Nombre", "Empresa", "Email", "Teléfono", "Servicio", "Mensaje", "Fecha Envío"};
            for (String encabezado : encabezados) {
                com.itextpdf.text.pdf.PdfPCell celda = new com.itextpdf.text.pdf.PdfPCell(new com.itextpdf.text.Phrase(encabezado));
                celda.setBackgroundColor(com.itextpdf.text.BaseColor.LIGHT_GRAY);
                celda.setHorizontalAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                tabla.addCell(celda);
            }

            // Agregar filas con los datos
            for (Contacto c : comentarios) {
                tabla.addCell(String.valueOf(c.getIdContacto()));
                tabla.addCell(c.getNombre());
                tabla.addCell(c.getEmpresa());
                tabla.addCell(c.getEmail());
                tabla.addCell(c.getTelefono());
                tabla.addCell(c.getServicio());
                tabla.addCell(c.getMensaje());
                tabla.addCell(c.getFechaEnvio().toString());
            }

            documento.add(tabla);
            documento.close();

            JOptionPane.showMessageDialog(this, "PDF generado correctamente en el escritorio.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar PDF: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnPDF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
