package Pantallas;

import Model.Dueno;
import Model.Cliente;
import Repositorio.AuthService;
import Repositorio.DuenoRepositorio;
import Repositorio.ClienteRepositorio;
import Util.Session;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;

public class NewLogin extends javax.swing.JFrame {

    /**
     * Creates new form NewLogin
     */
    public NewLogin() {
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png")).getImage());
        setResizable(false);
        initComponents();
        this.noVer.setVisible(false);//Ocultar boton "ojo"
        configurarPlaceholders();
        validacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        mensaje5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtContrasena = new javax.swing.JPasswordField();
        txtCorreo = new javax.swing.JTextField();
        ACEPTAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        noVer = new javax.swing.JLabel();
        ver = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Moroni | Login");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(195, 18, 1));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(195, 18, 1));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grua.gif"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 183, 331, 305));

        mensaje.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 255, 255));
        mensaje.setText("Servicios");
        jPanel2.add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 75, 185, 40));

        mensaje5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N
        mensaje5.setForeground(new java.awt.Color(255, 255, 255));
        mensaje5.setText("Moroni");
        jPanel2.add(mensaje5, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 121, 146, 50));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Construyendo un futuro sólido");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 494, 222, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 370, 610));

        jPanel3.setBackground(new java.awt.Color(18, 60, 109));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtContrasena.setBackground(new java.awt.Color(18, 60, 109));
        txtContrasena.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        txtContrasena.setForeground(new java.awt.Color(255, 255, 255));
        txtContrasena.setBorder(null);
        txtContrasena.setCaretColor(new java.awt.Color(255, 255, 255));
        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });
        jPanel3.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 384, 406, 32));

        txtCorreo.setBackground(new java.awt.Color(18, 60, 109));
        txtCorreo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(null);
        txtCorreo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCorreo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel3.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 290, 406, 32));

        ACEPTAR.setBackground(new java.awt.Color(153, 0, 0));
        ACEPTAR.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        ACEPTAR.setForeground(new java.awt.Color(255, 255, 255));
        ACEPTAR.setText("ACEPTAR");
        ACEPTAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEPTARActionPerformed(evt);
            }
        });
        jPanel3.add(ACEPTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 444, 131, 40));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Quien anda ahí?");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 153, 361, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 328, 456, 12));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 422, 450, 16));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lock.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 384, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/email.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 290, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 405, -1, -1));

        noVer.setBackground(new java.awt.Color(18, 60, 109));
        noVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eye.png"))); // NOI18N
        noVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noVerMouseClicked(evt);
            }
        });
        jPanel3.add(noVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, -1));

        ver.setBackground(new java.awt.Color(18, 60, 109));
        ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hide.png"))); // NOI18N
        ver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMouseClicked(evt);
            }
        });
        jPanel3.add(ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, 23));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 620, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean contrasenaPlaceholderActivo = true;
    private boolean contrasenaVisible = false;

    private void configurarPlaceholders() {
        // Correo
        txtCorreo.setText("Ingrese su Correo");
        txtCorreo.setForeground(new java.awt.Color(150, 150, 150));

        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtCorreo.getText().equals("Ingrese su Correo")) {
                    txtCorreo.setText("");
                    txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtCorreo.getText().isEmpty()) {
                    txtCorreo.setText("Ingrese su Correo");
                    txtCorreo.setForeground(new java.awt.Color(150, 150, 150));
                }
            }
        });

        // Contraseña
        txtContrasena.setText("Contraseña");
        txtContrasena.setForeground(new java.awt.Color(150, 150, 150));
        txtContrasena.setEchoChar((char) 0);
        contrasenaPlaceholderActivo = true;
        contrasenaVisible = false;

        txtContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (contrasenaPlaceholderActivo) {
                    txtContrasena.setText("");
                    txtContrasena.setForeground(new java.awt.Color(255, 255, 255));
                    contrasenaPlaceholderActivo = false;
                    // Cuando gana foco, respeta estado del ojo
                    if (!contrasenaVisible) {
                        txtContrasena.setEchoChar('•');
                    } else {
                        txtContrasena.setEchoChar((char) 0);
                    }
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (String.valueOf(txtContrasena.getPassword()).isEmpty()) {
                    txtContrasena.setText("Contraseña");
                    txtContrasena.setForeground(new java.awt.Color(150, 150, 150));
                    txtContrasena.setEchoChar((char) 0);
                    contrasenaPlaceholderActivo = true;
                }
            }
        });

    }


    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void validacion() {
        // Instancias de servicios/repositorios
        AuthService auth = new AuthService();
        ClienteRepositorio clienteRepo = new ClienteRepositorio();
        DuenoRepositorio duenoRepo = new DuenoRepositorio();

        System.out.println("===== VALIDACIÓN DE DATOS EXISTENTES EN BD =====");

        try {
            // CLIENTES
            List<Cliente> clientes = clienteRepo.obtenerTodos();
            System.out.println("\nCLIENTES REGISTRADOS (" + clientes.size() + "):");
            if (clientes.isEmpty()) {
                System.out.println("  No hay clientes registrados.");
            } else {
                for (Cliente c : clientes) {
                    System.out.println("  - " + c.getNombreCliente() + " | " + c.getEmailCliente() + " | " + c.getContrasenaCliente());
                }
            }

            // DUEÑOS
            List<Dueno> duenos = duenoRepo.obtenerTodos();
            System.out.println("\nDUEÑOS REGISTRADOS (" + duenos.size() + "):");
            if (duenos.isEmpty()) {
                System.out.println("  No hay dueños registrados.");
            } else {
                for (Dueno d : duenos) {
                    System.out.println("  - " + d.getNombreDueno() + " | " + d.getEmailDueno() + " | " + d.getContrasenaDueno());
                }
            }

            System.out.println("\n Conexion y validacion completadas correctamente.");

        } catch (Exception e) {
            System.err.println("❌ Error al obtener datos desde la base de datos: " + e.getMessage());
            e.printStackTrace();
        }
    }


    private void ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPTARActionPerformed
        String email = txtCorreo.getText().trim().toLowerCase();
        String contrasena = new String(txtContrasena.getPassword()).trim();

        if (email.isEmpty() || contrasena.isEmpty()
                || email.equalsIgnoreCase("ingrese su correo")
                || contrasena.equalsIgnoreCase("contraseña")) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, ingrese su correo y contraseña.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        AuthService auth = new AuthService();
        ClienteRepositorio clienteRepo = new ClienteRepositorio();
        DuenoRepositorio duenoRepo = new DuenoRepositorio();

        // 🔹 Validar Cliente
        if (auth.validarCredencialesCliente(email, contrasena)) {
            Cliente cliente = clienteRepo.verPorEmail(email);
            Session.iniciarSesionCliente(cliente);

            String rol = cliente.getRol(); // <- Asegúrate que exista getRol() en la clase Cliente

            if (rol != null) {
                if (rol.equalsIgnoreCase("ROLE_ADMIN")) {
                    JOptionPane.showMessageDialog(this,
                            "Bienvenido Administrador: " + cliente.getNombreCliente(),
                            "Ingreso Exitoso",
                            JOptionPane.INFORMATION_MESSAGE);
                    new PantallaAdmin(cliente).setVisible(true);
                } else if (rol.equalsIgnoreCase("ROLE_VISOR")) {
                    JOptionPane.showMessageDialog(this,
                            "Bienvenido Supervisor: " + cliente.getNombreCliente(),
                            "Ingreso Exitoso",
                            JOptionPane.INFORMATION_MESSAGE);
                    new PantallaSupervisor(cliente).setVisible(true);
                } else if(rol.equalsIgnoreCase("ROLE_DUENO")){
                    JOptionPane.showMessageDialog(this,
                            "Bienvenido Dueño: " + cliente.getNombreCliente(),
                            "Ingreso Exitoso",
                            JOptionPane.INFORMATION_MESSAGE);
                    new PantallaDueno(cliente).setVisible(true);
                }else {
                    JOptionPane.showMessageDialog(this,
                            "Rol desconocido: " + rol,
                            "Error de rol",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }

                this.dispose();
                return;
            } else {
                JOptionPane.showMessageDialog(this,
                        "El cliente no tiene un rol asignado.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }

        // 🔹 Validar Dueño
        /*if (auth.validarCredencialesDueno(email, contrasena)) {
            Dueno dueno = duenoRepo.verPorEmail(email);
            Session.iniciarSesionDueno(dueno);
            JOptionPane.showMessageDialog(this,
                    "Bienvenido Dueño: " + dueno.getNombreDueno(),
                    "Ingreso Exitoso",
                    JOptionPane.INFORMATION_MESSAGE);
            new PantallaDueno(dueno).setVisible(true);
            this.dispose();
            return;
        }*/

        // ❌ Ninguna coincidencia
        JOptionPane.showMessageDialog(this,
                "Credenciales incorrectas o usuario no registrado.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_ACEPTARActionPerformed

    private void verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMouseClicked
        txtContrasena.setEchoChar((char) 0);
        contrasenaVisible = true;
        ver.setVisible(false);
        noVer.setVisible(true);
    }//GEN-LAST:event_verMouseClicked

    private void noVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noVerMouseClicked
        if (!contrasenaPlaceholderActivo) {
            txtContrasena.setEchoChar('•');
        } else {
            txtContrasena.setEchoChar((char) 0);
        }
        contrasenaVisible = false;
        ver.setVisible(true);
        noVer.setVisible(false);
    }//GEN-LAST:event_noVerMouseClicked

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel mensaje5;
    private javax.swing.JLabel noVer;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JLabel ver;
    // End of variables declaration//GEN-END:variables
}
