package Pantallas;

import Model.Dueno;
import Model.Cliente;
import Repositorio.AuthService;
import Repositorio.DuenoRepositorio;
import Repositorio.ClienteRepositorio;
import Util.Session;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;

public class NewLogin extends javax.swing.JFrame {

    /**
     * Creates new form NewLogin
     */
    public NewLogin() {
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png")).getImage());

        initComponents();
        this.noVer.setVisible(false);//Ocultar boton "ojo"
        configurarPlaceholders();
        validacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        mensaje5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtContrasena = new javax.swing.JPasswordField();
        txtCorreo = new javax.swing.JTextField();
        ACEPTAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ver = new javax.swing.JLabel();
        noVer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(18, 60, 109));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grua.gif"))); // NOI18N

        mensaje.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 255, 255));
        mensaje.setText("Servicios");

        mensaje5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N
        mensaje5.setForeground(new java.awt.Color(255, 255, 255));
        mensaje5.setText("Moroni");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(mensaje5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        txtContrasena.setBackground(new java.awt.Color(51, 51, 51));
        txtContrasena.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        txtContrasena.setForeground(new java.awt.Color(255, 255, 255));
        txtContrasena.setBorder(null);
        txtContrasena.setCaretColor(new java.awt.Color(255, 255, 255));
        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });

        txtCorreo.setBackground(new java.awt.Color(51, 51, 51));
        txtCorreo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(null);
        txtCorreo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCorreo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        ACEPTAR.setBackground(new java.awt.Color(18, 60, 109));
        ACEPTAR.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        ACEPTAR.setForeground(new java.awt.Color(255, 255, 255));
        ACEPTAR.setText("ACEPTAR");
        ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEPTARActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(195, 18, 1));
        jLabel1.setText("¿Quien anda ahí?");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lock.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/email.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hide.png"))); // NOI18N
        ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMouseClicked(evt);
            }
        });
        jPanel4.add(ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 23));

        noVer.setBackground(new java.awt.Color(51, 51, 51));
        noVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eye.png"))); // NOI18N
        noVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noVerMouseClicked(evt);
            }
        });
        jPanel4.add(noVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)))
                        .addGap(59, 59, 59))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCorreo)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtContrasena))
                            .addComponent(jSeparator2))
                        .addGap(17, 17, 17)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(ACEPTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(97, 97, 97)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCorreo))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtContrasena)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addComponent(ACEPTAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, 586));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean contrasenaPlaceholderActivo = true;
    private boolean contrasenaVisible = false;

    private void configurarPlaceholders() {
        // Correo
        txtCorreo.setText("Ingrese su Correo");
        txtCorreo.setForeground(new java.awt.Color(150, 150, 150));

        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtCorreo.getText().equals("Ingrese su Correo")) {
                    txtCorreo.setText("");
                    txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtCorreo.getText().isEmpty()) {
                    txtCorreo.setText("Ingrese su Correo");
                    txtCorreo.setForeground(new java.awt.Color(150, 150, 150));
                }
            }
        });

        // Contraseña
        txtContrasena.setText("Contraseña");
        txtContrasena.setForeground(new java.awt.Color(150, 150, 150));
        txtContrasena.setEchoChar((char) 0);
        contrasenaPlaceholderActivo = true;
        contrasenaVisible = false;

        txtContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (contrasenaPlaceholderActivo) {
                    txtContrasena.setText("");
                    txtContrasena.setForeground(new java.awt.Color(255, 255, 255));
                    contrasenaPlaceholderActivo = false;
                    // Cuando gana foco, respeta estado del ojo
                    if (!contrasenaVisible) {
                        txtContrasena.setEchoChar('•');
                    } else {
                        txtContrasena.setEchoChar((char) 0);
                    }
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (String.valueOf(txtContrasena.getPassword()).isEmpty()) {
                    txtContrasena.setText("Contraseña");
                    txtContrasena.setForeground(new java.awt.Color(150, 150, 150));
                    txtContrasena.setEchoChar((char) 0);
                    contrasenaPlaceholderActivo = true;
                }
            }
        });

    }


    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void validacion() {
        // Instancias de servicios/repositorios
        AuthService auth = new AuthService();
        ClienteRepositorio clienteRepo = new ClienteRepositorio();
        DuenoRepositorio duenoRepo = new DuenoRepositorio();

        System.out.println("===== VALIDACIÓN DE DATOS EXISTENTES EN BD =====");

        try {
            // CLIENTES
            List<Cliente> clientes = clienteRepo.obtenerTodos();
            System.out.println("\nCLIENTES REGISTRADOS (" + clientes.size() + "):");
            if (clientes.isEmpty()) {
                System.out.println("  No hay clientes registrados.");
            } else {
                for (Cliente c : clientes) {
                    System.out.println("  - " + c.getNombreCliente() + " | " + c.getEmailCliente()+ " | " + c.getContrasenaCliente());
                }
            }

            // DUEÑOS
            List<Dueno> duenos = duenoRepo.obtenerTodos();
            System.out.println("\nDUEÑOS REGISTRADOS (" + duenos.size() + "):");
            if (duenos.isEmpty()) {
                System.out.println("  No hay dueños registrados.");
            } else {
                for (Dueno d : duenos) {
                    System.out.println("  - " + d.getNombreDueno() + " | " + d.getEmailDueno()+ " | " + d.getContrasenaDueno());
                }
            }

            System.out.println("\n Conexion y validacion completadas correctamente.");

        } catch (Exception e) {
            System.err.println("❌ Error al obtener datos desde la base de datos: " + e.getMessage());
            e.printStackTrace();
        }
    }


    private void ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPTARActionPerformed
        String email = txtCorreo.getText().trim().toLowerCase();
        String contrasena = new String(txtContrasena.getPassword()).trim();

        if (email.isEmpty() || contrasena.isEmpty()
                || email.equalsIgnoreCase("ingrese su correo")
                || contrasena.equalsIgnoreCase("contraseña")) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, ingrese su correo y contraseña.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        AuthService auth = new AuthService();
        ClienteRepositorio clienteRepo = new ClienteRepositorio();
        DuenoRepositorio duenoRepo = new DuenoRepositorio();

        // 🔹 Validar Cliente
        if (auth.validarCredencialesCliente(email, contrasena)) {
            Cliente cliente = clienteRepo.verPorEmail(email);
            Session.iniciarSesionCliente(cliente);

            String rol = cliente.getRol(); // <- Asegúrate que exista getRol() en la clase Cliente

            if (rol != null) {
                if (rol.equalsIgnoreCase("ROLE_ADMIN")) {
                    JOptionPane.showMessageDialog(this,
                            "Bienvenido Administrador: " + cliente.getNombreCliente(),
                            "Ingreso Exitoso",
                            JOptionPane.INFORMATION_MESSAGE);
                    new PantallaAdmin(cliente).setVisible(true);
                } else if (rol.equalsIgnoreCase("ROLE_USER")) {
                    JOptionPane.showMessageDialog(this,
                            "Bienvenido Cliente: " + cliente.getNombreCliente(),
                            "Ingreso Exitoso",
                            JOptionPane.INFORMATION_MESSAGE);
                    new PantallaCliente(cliente).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Rol desconocido: " + rol,
                            "Error de rol",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }

                this.dispose();
                return;
            } else {
                JOptionPane.showMessageDialog(this,
                        "El cliente no tiene un rol asignado.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }

        // 🔹 Validar Dueño
        if (auth.validarCredencialesDueno(email, contrasena)) {
            Dueno dueno = duenoRepo.verPorEmail(email);
            Session.iniciarSesionDueno(dueno);
            JOptionPane.showMessageDialog(this,
                    "Bienvenido Dueño: " + dueno.getNombreDueno(),
                    "Ingreso Exitoso",
                    JOptionPane.INFORMATION_MESSAGE);
            new PantallaDueno(dueno).setVisible(true);
            this.dispose();
            return;
        }

        // ❌ Ninguna coincidencia
        JOptionPane.showMessageDialog(this,
                "Credenciales incorrectas o usuario no registrado.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_ACEPTARActionPerformed

    private void verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMouseClicked
        txtContrasena.setEchoChar((char) 0);
        contrasenaVisible = true;
        ver.setVisible(false);
        noVer.setVisible(true);
    }//GEN-LAST:event_verMouseClicked

    private void noVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noVerMouseClicked
        if (!contrasenaPlaceholderActivo) {
            txtContrasena.setEchoChar('•');
        } else {
            txtContrasena.setEchoChar((char) 0);
        }
        contrasenaVisible = false;
        ver.setVisible(true);
        noVer.setVisible(false);
    }//GEN-LAST:event_noVerMouseClicked

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel mensaje5;
    private javax.swing.JLabel noVer;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JLabel ver;
    // End of variables declaration//GEN-END:variables
}
