package Pantallas;

import Model.Cliente;
import Model.Dueno;
import Vistas.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JPanel;

public class PantallaDueno extends javax.swing.JFrame {

    private Dueno dueno;

    /**
     * Creates new form PantallaDuenio
     */
    public PantallaDueno() {
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/180.png")).getImage());
        initComponents();
    }

    public PantallaDueno(Cliente cliente) {
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/180.png")).getImage());
        initComponents();
        // Verificar que labelNombres no sea null
        if (labelNombres != null && cliente != null) {
            labelNombres.setText(cliente.getNombreCliente());
        } else {
            System.err.println("No se pudo mostrar el nombre del Dueno.");
            if (labelNombres == null) {
                System.err.println("labelNombres es null.");
            }
            if (dueno == null) {
                System.err.println("instructor es null.");
            }
        }
        SetDate();
        initStyles();
        InitContent();
        botonUsuarios.setBackground(new Color(30, 45, 65));
        botonInstructores.setBackground(new Color(30, 45, 65));
        botonInventario.setBackground(new Color(30, 45, 65));
        botonRegresar.setBackground(new Color(30, 45, 65));
        botonSalir1.setBackground(new Color(30, 45, 65));
    }

    private void initStyles() {
        mensaje.putClientProperty("FlatLaf.styleClass", "h1");
    }

    private void SetDate() {
        LocalDate now = LocalDate.now();
        int año = now.getYear();
        int mes = now.getMonthValue();
        int dia = now.getDayOfMonth();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre",
            "Ostubre", "Noviembre", "Diciembre"};
        fecha.setText("Hoy es " + dia + " de " + meses[mes - 1] + " de " + año);
    }

//-------------Añadir nombre en la parte superior (Hola nombre)-----------------
    public void setNombre(String nombre) {
        labelNombres.setText(nombre);
    }

    private void InitContent() {
        mostrarJPanelUsuario(new TablaCliente());
    }

    private void mostrarJPanelUsuario(JPanel p) {
        TablaUsuario prin = new TablaUsuario();
        prin.setSize(797, 449);
        prin.setLocation(0, 0);

        contenedor.removeAll();
        contenedor.add(prin, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }

    private void mostrarJPanelAdministrador(JPanel p) {
        TablaClienteAdmin prinIns = new TablaClienteAdmin();
        prinIns.setSize(797, 449);
        prinIns.setLocation(0, 0);

        contenedor.removeAll();
        contenedor.add(prinIns, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }

    private void mostrarJPanelComentarios(JPanel p) {
        TablaComentarios prinInven = new TablaComentarios();
        prinInven.setSize(797, 449);
        prinInven.setLocation(0, 0);

        contenedor.removeAll();
        contenedor.add(prinInven, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        mensaje = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botonInventario = new javax.swing.JButton();
        botonUsuarios = new javax.swing.JButton();
        botonInstructores = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        mensaje5 = new javax.swing.JLabel();
        botonSalir1 = new javax.swing.JButton();
        mensaje2 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();
        mensaje1 = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();
        labelNombres = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla Dueño");

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(18, 60, 109));

        mensaje.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 255, 255));
        mensaje.setText("Servicios");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        botonInventario.setBackground(new java.awt.Color(195, 18, 1));
        botonInventario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonInventario.setForeground(new java.awt.Color(255, 255, 255));
        botonInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/construccion-del-calendario.gif"))); // NOI18N
        botonInventario.setText("Comentarios");
        botonInventario.setBorder(null);
        botonInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInventario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonInventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonInventarioMouseExited(evt);
            }
        });
        botonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInventarioActionPerformed(evt);
            }
        });

        botonUsuarios.setBackground(new java.awt.Color(195, 18, 1));
        botonUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        botonUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edificio_2.gif"))); // NOI18N
        botonUsuarios.setText("Usuarios");
        botonUsuarios.setBorder(null);
        botonUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonUsuariosMouseExited(evt);
            }
        });
        botonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuariosActionPerformed(evt);
            }
        });

        botonInstructores.setBackground(new java.awt.Color(195, 18, 1));
        botonInstructores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonInstructores.setForeground(new java.awt.Color(255, 255, 255));
        botonInstructores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casco.gif"))); // NOI18N
        botonInstructores.setText("Administradores");
        botonInstructores.setBorder(null);
        botonInstructores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInstructores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonInstructores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonInstructoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonInstructoresMouseExited(evt);
            }
        });
        botonInstructores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInstructoresActionPerformed(evt);
            }
        });

        botonRegresar.setBackground(new java.awt.Color(195, 18, 1));
        botonRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trabajo-en-progreso.gif"))); // NOI18N
        botonRegresar.setText("Regresar al login");
        botonRegresar.setBorder(null);
        botonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarMouseExited(evt);
            }
        });
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        mensaje5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N
        mensaje5.setForeground(new java.awt.Color(255, 255, 255));
        mensaje5.setText("Moroni");

        botonSalir1.setBackground(new java.awt.Color(195, 18, 1));
        botonSalir1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonSalir1.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.gif"))); // NOI18N
        botonSalir1.setText("Salir");
        botonSalir1.setBorder(null);
        botonSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSalir1MouseExited(evt);
            }
        });
        botonSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalir1ActionPerformed(evt);
            }
        });

        mensaje2.setBackground(new java.awt.Color(255, 255, 255));
        mensaje2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        mensaje2.setForeground(new java.awt.Color(255, 255, 255));
        mensaje2.setText("Dueño");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botonInventario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonInstructores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(mensaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mensaje5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(botonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonInstructores, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        header.setBackground(new java.awt.Color(18, 60, 109));

        fecha.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        mensaje1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        mensaje1.setText("Hola");

        contenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        labelNombres.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(mensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void botonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInventarioActionPerformed
        mostrarJPanelComentarios(new TablaCliente());
    }//GEN-LAST:event_botonInventarioActionPerformed

    private void botonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuariosActionPerformed
        mostrarJPanelUsuario(new TablaCliente());
    }//GEN-LAST:event_botonUsuariosActionPerformed

    private void botonInstructoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInstructoresActionPerformed
        mostrarJPanelAdministrador(new TablaCliente());
    }//GEN-LAST:event_botonInstructoresActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        NewLogin nlog = new NewLogin();
        this.setVisible(false);
        nlog.setVisible(true);
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonUsuariosMouseEntered
        botonUsuarios.setBackground(new Color(78, 80, 82));
    }//GEN-LAST:event_botonUsuariosMouseEntered

    private void botonUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonUsuariosMouseExited
        botonUsuarios.setBackground(new Color(30, 45, 65));
    }//GEN-LAST:event_botonUsuariosMouseExited

    private void botonInstructoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInstructoresMouseEntered
        botonInstructores.setBackground(new Color(78, 80, 82));
    }//GEN-LAST:event_botonInstructoresMouseEntered

    private void botonInstructoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInstructoresMouseExited
        botonInstructores.setBackground(new Color(30, 45, 65));
    }//GEN-LAST:event_botonInstructoresMouseExited

    private void botonInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInventarioMouseEntered
        botonInventario.setBackground(new Color(78, 80, 82));
    }//GEN-LAST:event_botonInventarioMouseEntered

    private void botonInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInventarioMouseExited
        botonInventario.setBackground(new Color(30, 45, 65));
    }//GEN-LAST:event_botonInventarioMouseExited

    private void botonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseEntered
        botonRegresar.setBackground(new Color(78, 80, 82));
    }//GEN-LAST:event_botonRegresarMouseEntered

    private void botonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseExited
        botonRegresar.setBackground(new Color(30, 45, 65));
    }//GEN-LAST:event_botonRegresarMouseExited

    private void botonSalir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalir1MouseEntered
        botonSalir1.setBackground(new Color(78, 80, 82));
    }//GEN-LAST:event_botonSalir1MouseEntered

    private void botonSalir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalir1MouseExited
        botonSalir1.setBackground(new Color(30, 45, 65));
    }//GEN-LAST:event_botonSalir1MouseExited

    private void botonSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalir1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInstructores;
    private javax.swing.JButton botonInventario;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonSalir1;
    private javax.swing.JButton botonUsuarios;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelNombres;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    private javax.swing.JLabel mensaje5;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
