package Pantallas;

import Model.Cliente;
import Repositorio.AuthService;
import Util.Session;
import Vistas.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class PantallaSupervisor extends javax.swing.JFrame {

//Recibe del NewLogin
    private Cliente cliente;

    /**
     * Creates new form PantallaDuenio
     */
    public PantallaSupervisor() {
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png")).getImage());
        initComponents();
    }

    public PantallaSupervisor(Cliente cliente) {
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png")).getImage());
        this.cliente = cliente;
        initComponents();

        // Verificar que labelNombres no sea null
        if (labelNombres != null && cliente != null) {
            labelNombres.setText(cliente.getNombreCliente());
        } else {
            System.err.println("No se pudo mostrar el nombre del instructor.");
            if (labelNombres == null) {
                System.err.println("labelNombres es null.");
            }
            if (cliente == null) {
                System.err.println("instructor es null.");
            }
        }

        SetDate();
        initStyles();
        InitContent();
        //aplicarColoresBotones();
    }

    private void initStyles() {
        mensaje.putClientProperty("FlatLaf.styleClass", "h1");
    }

    private void SetDate() {
        LocalDate now = LocalDate.now();
        int año = now.getYear();
        int mes = now.getMonthValue();
        int dia = now.getDayOfMonth();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre",
            "Ostubre", "Noviembre", "Diciembre"};
        fecha.setText("Hoy es " + dia + " de " + meses[mes - 1] + " de " + año);
    }

//-------------Añadir nombre en la parte superior (Hola nombre)-----------------
    public void setNombre(String nombre) {
        labelNombres.setText(nombre);
    }

    private void InitContent() {
        /* mostrarJPanelAgendarHorarios();*/
    }

    /*private void aplicarColoresBotones() {
        Color color = new Color(30, 45, 65);
        botonAgendarHorarios.setBackground(color);
        botonComprar.setBackground(color);
        botonActualizarDatos.setBackground(color);
        botonRegresar.setBackground(color);
        botonSalir1.setBackground(color);
    }*/

    /*
    private void mostrarJPanelAgendarHorarios() {
        TablaAgendarHorarios panel = new TablaAgendarHorarios();
        cargarPanel(panel);
    }

    private void mostrarJPanelComprar() {
        TablaComprar panel = new TablaComprar();
        cargarPanel(panel);
    }

    private void mostrarJPanelActualizarDatos() {
        TablaActualizarDatos panel = new TablaActualizarDatos(this.cliente);
        cargarPanel(panel);
    }
     */
    private void cargarPanel(JPanel panel) {
        panel.setSize(797, 449);
        panel.setLocation(0, 0);
        contenedor.removeAll();
        contenedor.add(panel, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        mensaje = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botonActualizarDatos = new javax.swing.JButton();
        mensaje4 = new javax.swing.JLabel();
        mensaje5 = new javax.swing.JLabel();
        mensaje3 = new javax.swing.JLabel();
        botonInstructores = new javax.swing.JButton();
        botonSalir1 = new javax.swing.JButton();
        botonUsuarios = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();
        mensaje1 = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();
        labelNombres = new javax.swing.JLabel();
        mensaje2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla Supervisor");

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(18, 60, 109));

        mensaje.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 255, 255));
        mensaje.setText("New ");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        botonActualizarDatos.setBackground(new java.awt.Color(195, 18, 1));
        botonActualizarDatos.setForeground(new java.awt.Color(255, 255, 255));
        botonActualizarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizarDatos.png"))); // NOI18N
        botonActualizarDatos.setText("Actualizar Datos");
        botonActualizarDatos.setBorder(null);
        botonActualizarDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonActualizarDatos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonActualizarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonActualizarDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonActualizarDatosMouseExited(evt);
            }
        });
        botonActualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarDatosActionPerformed(evt);
            }
        });

        mensaje4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N
        mensaje4.setForeground(new java.awt.Color(255, 255, 255));
        mensaje4.setText("Gym");

        mensaje5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N
        mensaje5.setForeground(new java.awt.Color(255, 255, 255));
        mensaje5.setText("Body");

        mensaje3.setBackground(new java.awt.Color(255, 255, 255));
        mensaje3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        mensaje3.setForeground(new java.awt.Color(255, 255, 255));
        mensaje3.setText("Supervisor");

        botonInstructores.setBackground(new java.awt.Color(195, 18, 1));
        botonInstructores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonInstructores.setForeground(new java.awt.Color(255, 255, 255));
        botonInstructores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casco.gif"))); // NOI18N
        botonInstructores.setText("Administradores");
        botonInstructores.setBorder(null);
        botonInstructores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInstructores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonInstructores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonInstructoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonInstructoresMouseExited(evt);
            }
        });
        botonInstructores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInstructoresActionPerformed(evt);
            }
        });

        botonSalir1.setBackground(new java.awt.Color(195, 18, 1));
        botonSalir1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonSalir1.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.gif"))); // NOI18N
        botonSalir1.setText("Salir");
        botonSalir1.setBorder(null);
        botonSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSalir1MouseExited(evt);
            }
        });
        botonSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalir1ActionPerformed(evt);
            }
        });

        botonUsuarios.setBackground(new java.awt.Color(195, 18, 1));
        botonUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        botonUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edificio_2.gif"))); // NOI18N
        botonUsuarios.setText("Usuarios");
        botonUsuarios.setBorder(null);
        botonUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonUsuariosMouseExited(evt);
            }
        });
        botonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuariosActionPerformed(evt);
            }
        });

        botonRegresar.setBackground(new java.awt.Color(195, 18, 1));
        botonRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trabajo-en-progreso.gif"))); // NOI18N
        botonRegresar.setText("Regresar al login");
        botonRegresar.setBorder(null);
        botonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresarMouseExited(evt);
            }
        });
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(mensaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonActualizarDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonInstructores, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(menuLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(mensaje4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(mensaje5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(mensaje4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mensaje5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje3)
                .addGap(84, 84, 84)
                .addComponent(botonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonInstructores, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonActualizarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(18, 60, 109));

        fecha.setBackground(new java.awt.Color(18, 60, 109));
        fecha.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        mensaje1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        mensaje1.setText("Hola");

        contenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 892, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        labelNombres.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(mensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mensaje2.setBackground(new java.awt.Color(255, 255, 255));
        mensaje2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 18)); // NOI18N
        mensaje2.setForeground(new java.awt.Color(255, 255, 255));
        mensaje2.setText("Dueño");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(491, 491, 491)
                    .addComponent(mensaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(587, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(313, 313, 313)
                    .addComponent(mensaje2)
                    .addContainerGap(342, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void botonActualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarDatosActionPerformed
        /* String email = cliente.getEmailCliente();
        String contrasenaIngresada = JOptionPane.showInputDialog(
                null,
                "Por motivos de seguridad, vuelva a ingresar su contraseña:",
                "Verificación de identidad",
                JOptionPane.INFORMATION_MESSAGE
        );

        if (contrasenaIngresada == null || contrasenaIngresada.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una contraseña válida.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        AuthService authService = new AuthService();
        boolean esValido = authService.validarCredencialesCliente(email, contrasenaIngresada);

        if (esValido) {
            mostrarJPanelActualizarDatos();
        } else {
            JOptionPane.showMessageDialog(null, "Contraseña incorrecta.", "Acceso denegado", JOptionPane.ERROR_MESSAGE);
        }*/
    }//GEN-LAST:event_botonActualizarDatosActionPerformed

    private void botonActualizarDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarDatosMouseEntered
//        botonActualizarDatos.setBackground(new Color(78, 80, 82));
    }//GEN-LAST:event_botonActualizarDatosMouseEntered

    private void botonActualizarDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarDatosMouseExited
//        botonActualizarDatos.setBackground(new Color(30, 45, 65));
    }//GEN-LAST:event_botonActualizarDatosMouseExited

    private void botonUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonUsuariosMouseEntered
//        botonUsuarios.setBackground(new Color(78, 80, 82));
    }//GEN-LAST:event_botonUsuariosMouseEntered

    private void botonUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonUsuariosMouseExited
//        botonUsuarios.setBackground(new Color(30, 45, 65));
    }//GEN-LAST:event_botonUsuariosMouseExited

    private void botonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuariosActionPerformed
        
    }//GEN-LAST:event_botonUsuariosActionPerformed

    private void botonInstructoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInstructoresMouseEntered
//        botonInstructores.setBackground(new Color(78, 80, 82));
    }//GEN-LAST:event_botonInstructoresMouseEntered

    private void botonInstructoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInstructoresMouseExited
//        botonInstructores.setBackground(new Color(30, 45, 65));
    }//GEN-LAST:event_botonInstructoresMouseExited

    private void botonInstructoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInstructoresActionPerformed

    }//GEN-LAST:event_botonInstructoresActionPerformed

    private void botonSalir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalir1MouseEntered
//        botonSalir1.setBackground(new Color(78, 80, 82));
    }//GEN-LAST:event_botonSalir1MouseEntered

    private void botonSalir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalir1MouseExited
//        botonSalir1.setBackground(new Color(30, 45, 65));
    }//GEN-LAST:event_botonSalir1MouseExited

    private void botonSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalir1ActionPerformed

    private void botonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseEntered
//        botonRegresar.setBackground(new Color(78, 80, 82));
    }//GEN-LAST:event_botonRegresarMouseEntered

    private void botonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseExited
//        botonRegresar.setBackground(new Color(30, 45, 65));
    }//GEN-LAST:event_botonRegresarMouseExited

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        NewLogin nlog = new NewLogin();
        this.setVisible(false);
        nlog.setVisible(true);
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarDatos;
    private javax.swing.JButton botonInstructores;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonSalir1;
    private javax.swing.JButton botonUsuarios;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelNombres;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    private javax.swing.JLabel mensaje3;
    private javax.swing.JLabel mensaje4;
    private javax.swing.JLabel mensaje5;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
